services:

  cardano-node-relay:
    build: .
    image: cardano-node-relay
    container_name: cardano-node-relay
    ports:
      - 6000:6000 # Cardano node relay port
      - 12798:12798 # Cardano node metrics
    volumes:
      - ./node/db/:/node/db
      - ./node/ipc/:/node/ipc
      - ./node/logs/:/node/logs

  node_exporter: # Listening by default on port 9100
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    depends_on:
      - cardano-node-relay

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - node_exporter

# check -> https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896/5
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000 # Grafana monitor port
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
